Ext.define('gsetrack.store.Autres', {
    extend: 'Ext.data.Store',
    config: {
        model: 'gsetrack.model.Autre',
        data: [{
            name: 'Aide',
            icon: 'icon-aide.png',
            contenu: "<h1>Aide</h1><h2>Navigation</h2><p>Les 5 onglets au bas de l'écran vous permettent d'accéder aux différents contenus. Lorsque vous vous sélectionnez un onglet spécifique vous disposez de nouvelles possibilités de navigation listées ci-dessous.</p><table class=\"contenu\"><tr><td style=\"padding: 3px; vertical-align: top;\"><img style=\"background-color: #008acb; padding: 5px;\" src=\"resources/icons/ville.png\" /></td><td><h3>Onglet &laquo;Général&raquo;</h3><p>Cet onglet vous donne une brève description du contenu de l’application et du contexte dans lequel elle a été conçue.</p></tr><tr><td style=\"padding: 3px; vertical-align: top;\"><img style=\"background-color: #008acb; padding: 5px;\" src=\"resources/icons/parcours.png\" /></td><td><h3>Onglet &laquo;parcours&raquo;</h3><p>Cet onglet affiche une carte interactive du parcours et des différents arrêts. Vous disposez des fonctions suivantes:<br /><ul><li><strong>Affichage des Postes:</strong> les postes sont représentés sous forme de cercles numérotés. En cliquant sur un poste vous accédez au descriptif de ce dernier. Depuis le descriptif il est possible de revenir à la carte en cliquant sur l’onglet <i>&laquo;Retour&raquo;</i> en haut à gauche de l’écran.</li><li><strong>Géo-localisation:</strong> Si vous avez autorisé l’application à localiser votre appareil mobile, votre position s’affiche sur la carte sous forme d’un cercle bleu.</li><li><strong>Zoom:</strong> A l’aide des icones <strong>+</strong> ou <strong>-</strong> en haut à gauche de l’écran vous pouvez agrandir ou diminuer la taille de la carte.</li><li><strong>Défilement de la carte:</strong> En maintenant un doigt sur la carte vous pouvez la faire défiler.</p></tr><tr><td style=\"padding: 3px; vertical-align: top;\"><img style=\"background-color: #008acb; padding: 5px;\" src=\"resources/icons/postes.png\" /></td><td><h3>Onglet &laquo;Postes&raquo;</h3><p>Grâce à cet onglet vous avez un accès direct au descriptif des différents postes sans passer par la carte interactive. Il vous suffit de cliquer sur le nom du poste pour accéder à son descriptif. Depuis le descriptif il est possible de revenir à la liste des postes en cliquant sur l’onglet <i>&laquo;Retour&raquo;</i> en haut à gauche de l’écran. Il est également possible d’obtenir plus d’informations sur les lieux visités à l’aide de l’onglet <em>&laquo;Suivant&raquo;</em>.</tr><tr><td style=\"padding: 3px; vertical-align: top;\"><img style=\"background-color: #008acb; padding: 5px;\" src=\"resources/icons/themes.png\" /></td><td><h3>Onglet &laquo;Thèmes&raquo;</h3><p>L'onglet &laquo;Thèmes&raquo; vous donne des informations sur chacune des thématiques traitées. Chaque poste est lié à une de ces thématiques.</p></tr></table>",
        },{
            name: 'Infos pratiques',
            icon: 'icon-info.png',
            contenu: "<h1>Infos pratiques</h1><h3>Itinéraire à la carte</h3><p>Les arrêts peuvent être consultés soit dans l'ordre, en parcourant l'itinéraire entièrement ou en partie, soit au gré de vos envies (via l'onglet thème ou postes) ou du lieu où vous vous trouvez (via l'onglet parcours). Orientez-vous en tout temps grâce à la carte de l'onglet parcours. La première page de chaque arrêt vous indique par une photo et une courte description où vous positionner avant de passer à la deuxième page, celle de l'explication.</p><h3>Accès en transports publics</h3><p>L'itinéraire complet commence à la tour de Sauvabelin que vous pouvez rejoindre en bus depuis Saint-François (bus n° 16, arrêt Signal). Il peut se parcourir entièrement à pieds, mais il est recommandé d'emprunter le métro m1 entre Vigie (arrêt 16) et Malley (arrêt 17). L'itinéraire se termine à l'université, d'où vous pouvez facilement rejoindre le centre-ville par le métro le m1.</p><h3>Equipement</h3><p>Pour, la partie supérieure (arrêts 2 à 4), des chaussures fermées peuvent se révéler utiles, surtout s'il a plu : le chemin n'est pas goudronné. Le reste de l'itinéraire ne pose aucun problème et peut être même, avec quelques adaptations, parcouru en chaise roulante. Dans ce cas, il est conseillé de commencer l'itinéraire sur la place de la Riponne (arrêt 9).</p><p>En été, plusieurs fontaines permettent de se rafraîchir en chemin.</p>",
        },{
            name: 'Crédits',
            icon: 'icon-credits.png',
            contenu: "<h1>Crédits</h1><hr /><h2>Coordination du projet</h2><p>Institut de géographie et durabilité et Faculté des géosciences et de l’environnement, Université de Lausanne</p><ul><li><a href=\"http://mesoscaphe.unil.ch/reynard/\">Emmanuel Reynard</a></li></ul><hr /><h2>Conception technique</h2><p>Institut de géographie et durabilité, FGSE-UNIL</p><ul><li><a href=\"http://mesoscaphe.unil.ch/ckaiser\">Christian Kaiser</a></li><li>Lucien Grangier</li></ul>Contact: <a href=\"mailto:christian.kaiser@unil.ch\">christian.kaiser@unil.ch</a></p><hr /><h2>Ligne graphique et contenu</h2><p><img src=\"resources/images/logo_relief.jpg\" /></p><p>Bureau Relief, Géotourisme & Patrimoine<br /><a href=\"http://www.bureau-relief.ch\">www.bureau-relief.ch</a></p><ul><li>Lenka Kozlik</li><li>Simon Martin</li><li>Amandine Perret</li><li>Géraldine Regolini-Bissig</li></ul>Contact: <a href=\"mailto:info@bureau-relief.ch\">info@bureau-relief.ch</a></p><hr /><h2>Groupes de recherche ayant fourni du contenu</h2><ul><li>IGD, groupe Etudes urbaines</li><li>IGD, groupe Etudes alpines</li><li>ISTE, groupe Ecotoxicologie (N. Chèvre)</li><li>EPFL, Laboratoire de technologie écologique (L. Rossi)</li></ul><hr /><h2>Licence</h2><p>GéoGuide est un projet open-source de l'Université de Lausanne. Le code source est disponible sous une licence GPL v3 depuis le site <a href=\"https://github.com/christiankaiser/geoguide\">https://github.com/christiankaiser/geoguide</a>. Le projet utilise d'autres projets open-source:<ul><li><a href=\"http://www.sencha.com/products/touch\">Sencha Touch</a></li><li><a href=\"http://leafletjs.com\">Leaflet JS</a></li></ul>Le matériel cartographique provient de <a href=\"http://www.openstreetmap.org/\">OpenStreetMap</a> et a été mis en forme à l'aide du logiciel <a href=\"http://www.mapbox.com/tilemill/\">TileMill</a>.</p>",
        },{
            name: 'Feedback',
            icon: 'icon-feedback.png',
            contenu: "<h1>Feedback</h1><p>La version actuelle du GéoGuide Lausanne est en version Bêta. Ça veut dire que l'application fonctionne bien dans la plupart des cas, mais nous n'avons pas encore assez d'expérience pour garantir que tout se passe bien dans tous les cas. Ça veut aussi dire que nous continuons à améliorer cette application.</p><p>Nous serions ravi d'avoir votre opinion, vos propositions, votre retour si quelque chose ne fonctionnait pas comme attendu etc. Contactez nous simplement par e-mail à l'adresse <a href=\"mailto:christian.kaiser@unil.ch\">christian.kaiser@unil.ch</a>.</p><p>Vous pouvez aussi consulter le site Web de l'application à l'URL <a href=\"http://igd.unil.ch/geoguide\">http://igd.unil.ch/geoguide</a>, où vous pouvez vous inscrire à notre newsletter pour recevoir les dernières infos, ou vous pouvez nous suivre sur Facebook ou Twitter.</p>",
        }]
    }
})