Ext.define('gsetrack.store.Postes', {
    extend: 'Ext.data.Store',
    config: {
        model: 'gsetrack.model.Poste',
        data: [
        {
            no: 1, 
            lieu: 'Tour de Sauvabelin', 
            accroche: 'Changer de point de vue pour voir notre monde autrement...',
            theme: 'ABC',
            photo_localisation: ['stop_1.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 1 se trouve au sommet de la grande tour en bois de Sauvabelin: il y a beaucoup de marches, mais la vue est superbe!</p>",
            contenu: [{
                'title': "Changer de point de vue pour voir notre monde autrement...",
                'illustration': [['fig_1.jpg', 'fig_1_AB.jpg', 'fig_1_AC.jpg', 'fig_1_BC.jpg',], 'S. Martin | Relief 2013'],
                'legend': "Dans notre environnement, tout est en relation: le relief naturel, les activités humaines et le climat s'influencent mutuellement. Pour en savoir plus, consultez l'onglet &laquo;Thème&raquo;.",
                'text': "<p>Du sommet de la tour de Sauvabelin, bâtie sur l'un des grands réservoirs d'eau potable de la ville, on peut contempler Lausanne et ses environs: des bois du Jorat aux rives du Léman, du Jura aux Alpes en passant par Lavaux. Observez les panneaux pour retrouver dans le paysage les lieux connus et inconnus...</p><p>Au cours de cette balade, nous vous proposerons souvent de changer de point de vue pour regarder les choses avec les yeux d'un chercheur en géosciences. La ville se met à vivre, les rivières font surface, le sous-sol des places révèle des mystères, le glacier du Rhône construit des collines, les toits de Lausanne se retrouvent dans l'eau du Léman... Des sujets passionnants et surprenants qui dévoileront quelques-uns des liens cachés entre le climat, les activités humaines et le relief naturel.</p>",
            },{
                'title': "Plus d'infos...",
                'text': "<p>Documentaire <em>La tour de Sauvabelin – couleur bois</a></em> à commander aux Archives de la Ville de Lausanne: <a href=\"http://www.lausanne.ch/ville-culturelle/histoire-et-patrimoine/archives-communales/publications/la-tour-de-sauvabelin-couleur-bois.html\">http://www.lausanne.ch/ville-culturelle/histoire-et-patrimoine/archives-communales/publications/la-tour-de-sauvabelin-couleur-bois.html</a></p>",
            }],
        },
        {
            no: 2, 
            lieu: 'Lac de Sauvabelin', 
            accroche: 'Le lac de nos souvenirs d’enfance qui n’existait pas il y a 125 ans!', 
            theme: 'AB',
            photo_localisation: ["stop_2.jpg", 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 2 se trouve au bord du lac de Sauvabelin. Si vous avez le temps, il est possible d'en faire le tour.</p>",
            contenu: [{
                'title': "Le lac de nos souvenirs d’enfance qui n’existait pas il y a 125 ans!",
                'illustration': [['fig_2.jpg',], '&copy; Musée historique de Lausanne, tous droits réservés'],
                'legend': "Patineurs sur le lac de Sauvabelin au début du XX<sup>e</sup> siècle.",
                'text': "<p>Des générations d'enfants lausannois se souviennent de balades dominicales autour du lac de Sauvabelin, ce bout de nature à deux pas de la ville où l’on peut nourrir des animaux. Pourtant, le lac n’est pas si naturel que ça! Il a en effet été créé en 1888 par la Société de développement de la Ville de Lausanne qui voulait aménager un lieu de villégiature offrant la possibilité de se détendre et de faire du canotage. L’eau du lac provient des sources – naturelles – situées dans la forêt de Sauvabelin. La création du lac de Sauvabelin est donc le fruit de la volonté humaine et de conditions naturelles favorables.</p>",
            },{
                'title': "Plus d'infos...",
                'text': "<p>Informations sur Sauvabelin sur le site des Parcs et promenades de la Ville de Lausanne: <a href=\"http://www.lausanne.ch/ville-de-nature/espaces-verts/parcs-et-promenades/les-sites-de-loisirs/site-de-sauvabelin.html\">http://www.lausanne.ch/ville-de-nature/espaces-verts/parcs-et-promenades/les-sites-de-loisirs/site-de-sauvabelin.html</a></p>",
            }],
        },
        {
            no: 3, 
            lieu: 'Cascade du Flon', 
            accroche: '',
            theme: 'AC',
            photo_localisation: ['stop_3.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 3 se trouve devant la plus belle cascade du Flon. Le sentier qui y mène est en cul-de-sac.</p>",
            contenu: [{
                'title': "Ne confondez pas les cascades aménagées par les glaciers et affinées par l’eau et celles créées par la main de l’homme!",
                'illustration': [['fig_3a.jpg', 'fig_3b.jpg'], 'S. Martin | Relief 2013'],
                'legend': "Cascade du Flon, quelques mètres en aval de l'arrêt. La rivière saute la couche solide de grès (orange) et creuse au dessous la couche tendre de marnes (vert). Peu à peu, la couche de grès s'effrite et la cascade recule.",
                'text': "<p>Observez attentivement le lit du cours d’eau et ses cascades. Certaines sont naturelles. Elles sont dues à l’alternance de roches sableuses, épaisses et massives et de roches argileuses, plus fines et moins résistantes. Au cours des deux derniers millions d’années, les glaciers qui ont recouvert plusieurs fois Lausanne ont creusé différemment les roches dures et celles qui sont plus tendres. Lors de la fonte des glaces, les rivières ont poursuivi le travail des glaciers. Ce sont les couches sableuses (les bancs de grès) qui ont le mieux résisté à l’assaut de la glace et des cours d’eau. Aujourd’hui, l’érosion est devenue bien moins active : le ruisseau du Flon descend ces marches d’escalier en cascades.</p><p>L’homme a pris ensuite le relais pour aménager le lit du Flon et créer de petites cascades à l’aide de blocs de pierres afin de diminuer la vitesse du courant lors des orages.</p>",
            },],
        },
        {
            no: 4, 
            lieu: 'Dérivation du Flon', 
            accroche: "Lausanne utilise ses cours d'eau comme égouts!",
            theme: 'AB',
            photo_localisation: ['stop_4.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 4 est situé là où le Flon disparaît, dérivé vers la Vuachère, et que s'ouvrent les égouts de Lausanne.</p>",
            contenu: [{
                'title': "Lausanne utilise ses cours d'eau comme égouts!",
                'illustration': [['fig_4.jpg',], 'D. Bochatay 2004 | modifié G. Regolini | Relief 2013'],
                'legend': "Tracés des eaux claires et usées du Flon et de la Louve (Bochatay, 2004, modifié).",
                'text': "<p>Il fut un temps où les cours d'eau de Lausanne comme le Flon et la Louve étaient des égouts à part entière. Véritables cloaques, ils traversaient la ville en accueillant sur leur passage les déchets liquides et solides des artisans et habitants avant de se jeter dans le Léman.</p><p>Ces conditions perdurent du Moyen-Age jusqu'au XIX<sup>e</sup> siècle. Les autorités commencent alors à se préoccuper sérieusement des maladies et épidémies qui sévissent depuis longtemps parmi les habitants des quartiers défavorisés situés au bord des cours d'eau.</p><p>Par mesure d'hygiène et d'assainissement, des travaux de voûtage du Flon (entre 1873 et 1960) et de la Louve (entre 1812 et 1840) sont entrepris. Ces cours d'eau pollués coulent dès lors en sous-sol et n’incommodent plus les habitants. Depuis, le système de récolte des eaux usées continue d’emprunter le tracé naturel des anciens cours d’eau de Lausanne, mais il a connu bien des améliorations. En 1996 en particulier, le Flon a été dérivé ici en direction de la Vuachère afin d'éviter une trop grande dilution des eaux usées des égouts par les eaux claires de la rivière. Dix ans plus tard, la Louve a vu elle aussi ses eaux détournées et directement restituées au lac Léman, améliorant encore d'avantage l'efficacité du système d'épuration.</p>",
            },],
        },
        {
            no: 5, 
            lieu: 'Paroi de molasse', 
            accroche: 'tre bancs de sable et amas boueux, attention où vous posez les pieds!',
            theme: 'AC',
            photo_localisation: ['stop_5.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 5 se trouve au pied d'une paroi de molasse le long du chemin. Touchez de la main cette roche fragile composée ici essentiellement de sable.</p>",
            contenu: [{
                'title': "Entre bancs de sable et amas boueux, attention où vous posez les pieds!",
                'illustration': [['fig_5.jpg',], 'O. Heer 1864'],
                'legend': "Reconstitution du paysage lausannois à l'époque de la formation de la molasse d'eau douce, d'après les fossiles trouvés dans la région (Oswald Heer, 1864).",
                'text': "<p>Les arbres courbés et penchés qui se retenaient aux berges du Flon nous signalaient déjà sur le chemin le phénomène : les talus boueux au-dessus du chemin glissent lentement en direction de la rivière. L’alternance entre les roches dures (sable) et les roches tendres (argile) qui composent la molasse grise de Lausanne rend ce terrain bien fragile...</p><p>Fermez maintenant les yeux et imaginez le paysage dans lequel se sont formées ces différentes roches. Arrachés aux Alpes, il y a de cela environ 25 millions d’années et transportés par des rivières sur des centaines de kilomètres, les grains de sables se sont déposés et sédimentés pour former une roche relativement dure mais friable : le grès. Les couches en mouvement sont quant à elles formées de roches composées d'argile : les marnes. Au contact de l’eau, les marnes deviennent « visqueuses » et sont souvent à l’origine des glissements de terrain.</p>",
            },],
        },
        {
            no: 6, 
            lieu: 'Place du Vallon', 
            accroche: 'Bienvenue à Lausanne-les-Bains!',
            theme: 'BC',
            photo_localisation: ['stop_6.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 6 est situé sur la place du Vallon, face au bâtiment de l'ancien funiculaire qui menait à Sauvabelin.</p>",
            contenu: [{
                'title': "Bienvenue à Lausanne-les-Bains! L'histoire mouvementée d'un quartier les pieds dans l'eau.",
                'illustration': [['fig_6a.jpg', 'fig_6b.jpg', 'fig_6c.jpg',], '&copy; Musée historique de Lausanne, tous droits réservés'],
                'legend': "Trois différents visages du Vallon  les anciens bains thermaux, le funiculaire et les populaires bains Haldimand.",
                'text': "<p>Niché au fond de la vallée du Flon – d'où son nom – le quartier du Vallon a changé plusieurs fois de visage aux cours des siècles. Au XVIII<sup>e</sup> siècle, c'est son heure de gloire: la haute société s'y rend pour y &laquo;prendre les eaux&raquo; dans des bains thermaux (situés à l'emplacement du n°12) alimentés par une source ferrugineuse recommandée par les médecins. Le vallon est orné d'une promenade plantée d'arbres et d'un pavillon des bains. Au tournant du XX<sup>e</sup> siècle, tout cela disparaît. Le quartier attire cependant toujours les touristes qui, de 1899 à 1948, pouvaient monter jusqu'au tout nouveau lac de Sauvabelin grâce à un funiculaire dont la gare de départ subsiste.</p><p>Mais au début du XX<sup>e</sup> siècle, le quartier, devenu industriel, se distingue surtout par son insalubrité. Pour améliorer l'hygiène, on crée les Bains et Buanderie Haldimand, destinés cette fois à la population ouvrière qui ne  dispose pas d'eau courante. Ces bains sont alimentés par une eau sans minéralisation particulière, la source ferrugineuse ayant été perdue. La construction en 1958 de l'usine d'incinération du Vallon, à 200 mètres d'ici, n'améliore de loin pas l'image du quartier. Durant ces dernières années, le Vallon a aussi accueilli divers squats et une part de la scène alternative lausannoise.</p><p>Aujourd'hui, l'ancienne usine d'incinération a été remplacée par celle de Tridel, laissant le quartier respirer. Cette disparition laisse de la place pour imaginer un nouvel avenir au quartier. Les habitants sont consultés et participent à la définition des projets d'aménagement... Peut-être que l'on verra un jour des bains réapparaître dans ce quartier si changeant!",
            },],
        },
        {
            no: 7, 
            lieu: 'Tunnel de la Barre', 
            accroche: 'La ceinture Pichard ou comment défier le relief lausannois',
            theme: 'AC',
            photo_localisation: ['stop_7.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 7 se trouve à côté de l'arrêt de bus Place du Nord, face au tunnel.</p>",
            contenu: [{
                'title': "La ceinture Pichard, ou comment défier le relief lausannois.",
                'illustration': [['fig_7a.jpg', 'fig_7b.jpg',], 'C. Duboux 2001 in <i>Lausanne, un lieu, un bourg, une ville</i> | modifié S. Martin | Relief 2013'],
                'legend': "Le tunnel creusé à travers la molasse de la Barre facilite grandement le passage entre la vallée du Flon et celle de la Louve.",
                'text': "Tout cycliste s'aventurant à Lausanne sait que le relief de cette ville est tout sauf plat. C'était plus encore le cas lorsque les vallons du Flon et de la Louve n'étaient pas encore comblés et que l'éperon de la Barre constituait un obstacle difficile à franchir.</p><p>Pour mieux se déplacer à Lausanne, le premier ingénieur cantonal vaudois, Adrien Pichard, élabore un concept de circulation: la &laquo;ceinture Pichard&raquo;. La construction de cette ceinture routière (1836-1860) neutralise en grande partie la topographie lausannoise.</p><p>Au nord de la ville, le tunnel de la Barre, long de 56 mètres, relie les profonds vallons du Flon et de la Louve à l’endroit où ces deux cours d’eau se rapprochent et marquent un resserrement avant de circonscrire la colline de la Cité. Le vallon du Flon est traversé grâce à la construction magistrale du Grand Pont, qui constitua longtemps l'une des principales attractions touristiques de Lausanne.</p><p>Au début du XX<sup>e</sup> siècle la ceinture Pichard est complétée par d'autres ouvrages comme les ponts Chauderon (1904-1905) et Bessières (1908-1910). Les conditions de circulation ainsi nettement améliorées favorisent le développement de la ville.",
            },],
        },
        {
            no: 8, 
            lieu: 'Place de la Cathédrale', 
            accroche: 'Des constructions locales et durables et une matière première vivante',
            theme: 'BC',
            photo_localisation: ['stop_8.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 8 est situé à la place de la Cathédrale, devant le n°5. De l'autre côté de la Cathédrale, vous pouvez visiter le <b>musée historique de Lausanne</b> et en particulier sa magnifique maquette de la ville au XVII<sup>e</sup> siècle, lorsque le Flon et la Louve servaient encore à actionner des moulins.</p>",
            contenu: [{
                'title': "Des constructions locales et durables et une matière première vivante.",
                'illustration': [['fig_8a.jpg', 'fig_8b.jpg', 'fig_8c.jpg',], 'S. Martin | Relief 2013'],
                'legend': "Molasse, calcaire et gneiss: trois roches utilisées pour la construction des bâtiments et des trottoirs de la Cité.",
                'text': "Locales? Oui! Les matériaux de construction de la plupart des édifices de la Cité proviennent des carrières de molasse lausannoise exploitées par le passé autour du vieux bourg et des vallées du Flon et de la Louve. Durables? Oui, mais sensibles à la pluie et à la pollution. Les bâtiments en molasse nécessitent des travaux d’entretien et de restauration réguliers. Voyez-vous quelques-uns de ces blocs rongés chimiquement par l'air et l'humidité?</p><p>La molasse, mais aussi d'autres roches comme le calcaire, utilisé par exemple pour les marches d'escalier, contiennent les restes fossiles d'animaux et de végétaux d’espèces tropicales. Ouvrez l’œil! Ces témoins sont parfois visibles sur les façades des murs de la Cité. Ils racontent une histoire climatique tropicale bien différente de celle d’aujourd’hui.</p>",
            },],
        },
        {
            no: 9, 
            lieu: 'Place de la Riponne', 
            accroche: 'La valse des pelleteuses: combler et creuser le vallon de la Louve!',
            theme: 'AB',
            photo_localisation: ['stop_9.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 9 se trouve au coin de la terrasse accessible par les escaliers qui longent le palais de Rumine. Ce bâtiment abrite entre autres le <b>musée cantonal de Géologie</b> qui permet de découvrir l'histoire de la formation des Alpes ainsi que de nombreux fossiles et minéraux extraordinaires.</p>",
            contenu: [{
                'title': "La valse des pelleteuses: combler et creuser le vallon de la Louve.",
                'illustration': [['fig_9.jpg',], ''],
                'legend': "Vue de la place de la Riponne avec au centre la Grenette (marché couvert) et à l'arrière-plan la Cathédrale",
                'text': "<p>Au cours du XIX<sup>e</sup> siècle, la ville de Lausanne manque cruellement d'espace pour se développer.</p><p>Les vallons de la Louve et du Flon qui, jusqu'ici, étaient utile à la défense de la ville, sont devenus un frein à son développement. Les autorités décident alors de combler les vallons pour enterrer les cours d'eau pollués (voir Arrêt 4) et de créer des espaces publics.</p><p>Le voûtage du Flon permet la création de la place Pépinet et de la rue Centrale. La place de la Riponne, elle, est issue du voûtage de la Louve et du comblement de son vallon (1812-1840). A l'interface entre la ville et la campagne, la place de la Riponne abrite à cette époque le marché aux chevaux et une partie du marché artisanal.</p><p>Avec la création de la place de la Riponne, l’histoire du vallon de la Louve n’est cependant pas terminée. En 1976, des pelleteuses creusent la place et mettent le vallon temporairement à ciel ouvert pour permettre la construction du parking souterrain de la Riponne. Trente ans plus tard, les pelleteuses sont de retour: une partie de la place de la Riponne est de nouveau excavée dans le cadre de la construction du M2, Métro de Lausanne qui relie depuis 2008 Ouchy à Epalinges. À quand les prochains travaux?</p>",
            },{
                'title': "Plus d'infos...",
                'text': "<p>Reportage de 1968 sur la construction du parking souterrain de la Riponne: <a href=\"http://www.notrehistoire.ch/video/view/623/\">http://www.notrehistoire.ch/video/view/623/</a></p>",
            }],
        },
        {
            no: 10, 
            lieu: 'Louve souterraine', 
            accroche: "Découvrez l'un des cours d'eau enterré de Lausanne",
            theme: 'AB',
            photo_localisation: ['stop_10.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 10 est souterrain: descendez au niveau -3 du parking (escaliers ou ascenseur) et suivez les indications des trois photos pour découvrir où se cache la Louve.</p>",
            contenu: [{
                'title': "Découvrez l'un des cours d'eau enterré de Lausanne",
                'illustration': [[{file: 'fig_10.mp4', size: [510, 278], poster: 'fig_10.jpg'},], ''],
                'legend': "Film du service d'assainissement de Lausanne présentant la dérivation de la Louve.",
                'text': "<p>Entre 1812 et 1840, des travaux de voûtage et de comblement ont fait disparaître la Louve du paysage urbain. Pour l'apercevoir, il faut se rendre dans le parking souterrain de la Riponne où un regard permet de l'observer sur un petit tronçon. Selon les conditions météorologiques, vous apercevez un petit ruisseau ou un cours d'eau turbulent.</p><p>Une station de mesure installée sur la Louve permet de visualiser son débit, c'est-à-dire la quantité d'eau qui s'écoule en une seconde en un point donné de la rivière. Le débit de la Louve est fortement influencé par les travaux d'aménagements et les effets de l'urbanisation. Par rapport à un cours d'eau similaire à l'état naturel, les pics de débit des crues de la Louve sont beaucoup plus accentués (voir figure). Cet effet est dû à l'imperméabilisation des surfaces construites qui empêchent en grande partie l'infiltration des eaux de pluies. Ces dernières vont directement rejoindre le cours d'eau au lieu d'être retenues dans le sol.</p><p>Des travaux ont aussi été entrepris pour dériver les eaux claires de la Louve jusqu'au déversoir situé sous la Vallée de la Jeunesse. La Louve se trouve ainsi privée d'une part de son eau, ce qui réduit surtout les pics de débit. Ce que vous observez depuis le regard n'est que le résidu de la Louve qui, autrefois, traversait la ville à ciel ouvert.</p>",
            },],
        },
        {
            no: 11, 
            lieu: 'Place St Laurent', 
            accroche: "Un fragile équilibre, hérité de l'époque glaciaire, est rompu par le creusement du métro... et voilà qu'une place s'effondre!",
            theme: 'BC',
            photo_localisation: ['stop_11.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 11 correspond à la place Saint-Laurent. Le chemin entre les arrêts 10 et 11 passe par la gare du métro m2.</p>",
            contenu: [{
                'title': "Un fragile équilibre, hérité de l'époque glaciaire, est rompu par le creusement du métro... et voilà qu'une place s'effondre!",
                'illustration': [['fig_11a.gif', 'fig_11b.gif', 'fig_11c.gif'], 'S. Martin | Relief 2013'],
                'legend': null,
                'text': "<p>Mardi 22 février 2005, grosse surprise sur le chantier du creusement du métro m2: comme dans un sablier, eau, sable et gravats s'écoulent à travers le &laquo;plafond&raquo; du tunnel et laissent à la surface un gros trou. Que s'est-il passé? Pour mieux comprendre, remontons quelque 25’000 ans en arrière...</p><p>A cette époque, le glacier du Rhône recouvre une grande partie de la région. Sur sa bordure, les cailloux et rochers transportés depuis les Alpes par la glace s'entassent et créent une moraine. Cette crête de matériaux meubles joue le rôle d’un barrage. Derrière, là où se trouve aujourd'hui Saint-Laurent, un lac se forme.<br /><img src=\"resources/proj/fig_11a.gif\" style=\"width: 100%; max-width: 886px;\" /><br />Peu à peu, ce lac se remplit de sable, devient un marais, puis finit par s'assécher. Les Lausannois trouveront ce replat bien pratique pour y construire l'église Saint-Laurent, la place et tous les bâtiments qui l'entourent.<br /><img src=\"resources/proj/fig_11b.gif\" style=\"width: 100%; max-width: 886px;\" /><br />Mais les dépôts du lac et du marais ne sont pas de la pierre: ils ressemblent plutôt à du sable gorgé d'eau. Le chantier du tunnel du métro, en perçant le fond de l'ancien lac, a rompu l'équilibre. Une partie de ce qui se trouvait au-dessus s'est effondré.<br /><img src=\"resources/proj/fig_11c.gif\" style=\"width: 100%; max-width: 886px;\" /><br />Aujourd'hui, la place a retrouvé sa solidité, mais le sous-sol de Lausanne réserve encore bien des surprises!</p>",
            },{
                'title': "Plus d'infos...",
                'text': "Photo de la catastrophe, article <a href=\"http://www.unil.ch/mcg/page17692.html\">http://www.unil.ch/mcg/page17692.html</a>",
            }],
        },
        {
            no: 12, 
            lieu: 'Place Pépinet', 
            accroche: 'Pouvez-vous imaginer que deux rivières se rejoignent ici, juste sous vos pieds?',
            theme: 'AC',
            photo_localisation: ['stop_12.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 12 est situé à l’extrémité de la place, au bord de la rue Centrale, face au restaurant Les Brasseurs.</p>",
            contenu: [{
                'title': "Pouvez-vous imaginer que deux rivières se rejoignent ici, juste sous vos pieds?",
                'illustration': [['fig_12.jpg',], 'S. Martin | Relief 2013'],
                'legend': "Confluence du Flon et de la Louve devant la place Pépinet. L'image est fausse bien sûr : les deux rivières coulent plusieurs mètres en-dessous de la surface de la route.",
                'text': "<p>Les rues et les bâtiments cachent aujourd'hui la nature de cet endroit. Pourtant, plusieurs indices nous permettent de reconstituer le tableau. La rue Centrale, devant vous, a été créée en comblant la vallée du Flon qui s'écoule aujourd'hui en sous-sol, dans une galerie. Observez, à gauche, comme la ligne des maisons tourne en suivant les versants de l'ancienne vallée qui descend en pente douce vers vous. La rivière continue à votre droite et passe sous les arches du Grand-Pont. Nous la retrouverons plus tard.</p><p>Derrière vous arrive la Louve qui, après avoir traversé la Riponne, descend la rue... de la Louve bien sûr! Elle se jette dans le Flon juste sous vos pieds, sous la place Pépinet. C'est ainsi que la colline de la Cité, avec la cathédrale, se trouvait autrefois presque entièrement entourée d'eau, comme une île au cœur de la ville. Comme partout où deux rivières se rejoignent, le lieu était très humide. La place de la Palud, toute proche, nous le rappelle: son nom veut dire &laquo;Place du Marais&raquo;.</p>",
            },],
        },
        {
            no: 13, 
            lieu: 'Passerelle du Flon, milieu', 
            accroche: 'Du ballet de marchandise aux bals des étudiants',
            theme: 'BC',
            photo_localisation: ['stop_13.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 13 se trouve sur la passerelle du Flon, près de l'ascenseur, face à la voie du Chariot, la rue qui traverse le quartier du Flon en contre-bas.</p>",
            contenu: [{
                'title': "Du ballet des marchandises aux bals des étudiants.",
                'illustration': [['fig_13.jpg',], '&copy; Musée historique de Lausanne, phot. A. Kern'],
                'legend': "Au tournant du XX<sup>e</sup> siècle, les entrepôts fleurissent dans le quartier du Flon qui était une zone industrielle à cette époque.",
                'text': "<p>La nuit, la vie dans le quartier du Flon bat son plein. De nombreux bars et lieux de sortie nocturne caractérisent aujourd'hui cet endroit qui, autrefois, était un lieu de transit pour les marchandises.</p><p>Depuis sa création à la fin du XIXe siècle par comblement du vallon du Flon, le quartier homonyme est très dynamique. Zone industrielle d'abord, le quartier du Flon comprend un port franc et une gare de marchandise. Les biens acheminés par la &laquo;ficelle&raquo; (l’ancien métro) reliant le Flon à la gare ferroviaire et au port d'Ouchy transitent dans les entrepôts qui fleurissent dans la zone.</p><p>Des activités artisanales, créatives et récréatives prennent le relais à partir de l'après-guerre, lorsque les entrepôts perdent progressivement leur fonction. Après une période plutôt tranquille durant laquelle le site se dégrade, la ville cherche à réhabiliter le quartier du Flon en adoptant le plan partiel d'affectation (PPA) en 1999. Les travaux entrepris depuis vont progressivement transformer le quartier en un site où infrastructures de transport (m1, m2, LEB), grands commerces, loisirs et administrations se côtoient et où des bâtiments anciens se mêlent aux reconstructions.</p>",
            },{
                'title': "Plus d'infos...",
                'text': '<p><a href="http://fr.wikipedia.org/wiki/Le_Flon_(Lausanne)">http://fr.wikipedia.org/wiki/Le_Flon_(Lausanne)</a><br /><a href="http://www.lausanne.ch/ville-culturelle/histoire-et-patrimoine/architecture-et-monuments/urbanisme-aujoudhui/quartier-du-flon.html">http://www.lausanne.ch/ville-culturelle/histoire-et-patrimoine/architecture-et-monuments/urbanisme-aujoudhui/quartier-du-flon.html</a></p>'
            }],
        },
        {
            no: 14, 
            lieu: 'Passerelle du Flon, sud', 
            accroche: "En faisant un grand virage, une route nous rappelle comment le cours des rivières a été bouleversé... il y a 25'000 ans.",
            theme: 'AC',
            photo_localisation: ['stop_14.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 14 est situé à l'extrémité de la passerelle du Flon, près des ascenseurs menant à la gare du métro, face au Grand-Pont.</p>",
            contenu: [{
                'title': "En faisant un grand virage, une route nous rappelle comment le cours des rivières a été bouleversé... il y a 25'000 ans.",
                'illustration': [['fig_14.jpg',], 'S. Martin | Relief 2013'],
                'legend': "Au lieu de filer naturellement vers le sud, le Flon est forcé de virer à l'ouest pour contourner la moraine de Montbenon (en gris).",
                'text': "<p>Le Flon, caché en sous-sol, descend la rue Centrale, passe sous le Grand-Pont et arrive sur la place de l'Europe. La route principale suit tout le long le tracé du cours d'eau. Mais que se passe-t-il? Juste après les arches du pont, la route (et le Flon en dessous d'elle) tourne brusquement avant de continuer tout droit à travers le quartier du Flon. Sauriez-vous expliquer ce changement de direction?</p><p>Normalement, lorsque la pente est forte, comme à Lausanne, les rivières s'écoulent sans détour: le Flon aurait dû prendre le même chemin que le métro, direct jusqu'à Ouchy. Quelle force l'a-t-il détourné du droit chemin? C’est le glacier du Rhône qui, il y a 25'000 ans occupait la cuvette du Léman. Le climat était alors plus froid de 8 degrés environ qu’à l’heure actuelle. Le glacier à laissé ici de côté une imposante moraine, l'actuelle colline de Montbenon que rejoint cette passerelle. Le Flon a été obligé de longer cet obstacle en direction de l'ouest. Ce n'est qu'à Vidy qu'il pourra enfin retrouver le Léman, mais ceci est une autre histoire...</p>",
            },],
        },
        {
            no: 15, 
            lieu: 'Esplanade de Montbenon', 
            accroche: 'Dans la famille des moraines de Lausanne, qui est la plus vieille? Un petit jeu pour découvrir que les glaciers ne tiennent pas longtemps en place...',
            theme: 'AC',
            photo_localisation: ['stop_15.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 15 est tout au bord de l'esplanade, face au lac et à la colline boisée de Montriond.</p>",
            contenu: [{
                'title': "Dans la famille des moraines de Lausanne, qui est la plus vieille? Un petit jeu pour découvrir que les glaciers ne tiennent pas longtemps en place...",
                'illustration': [['fig_15.jpg',], 'S. Martin | Relief 2013'],
                'legend': "Positions du glacier du Rhône lors du dépôt des moraines de Montbenon et Montriond ; le retrait se poursuit ensuite. Le profil du relief lausannois est exagéré trois fois.",
                'text': "<p>En se déplaçant, tous les glaciers transportent d'innombrables fragments de roches arrachés au fond et aux bords des vallées ou éboulés sur la glace. Ces matériaux rocheux peuvent être plus petits qu'un grain de sable... ou aussi gros qu'une maison!</p><p>Quand le climat est favorable – froid, humide – le glacier progresse vers l'aval, emportant avec lui de très nombreux morceaux de roche. S'il se forme autant de glace en montagne qu'il n'en fond en plaine, le glacier cesse alors de progresser: la glace continue de couler vers l'aval, mais le front du glacier reste à la même place durant plusieurs années. Les morceaux de roche, toujours transportés par la glace, s'empilent tous au même endroit dans la plaine. C'est ainsi qu'à chaque arrêt du glacier se crée à sa hauteur une moraine, comme celle de Montbenon.</p><p>Mais le climat change sans cesse. Si les températures augmentent beaucoup, le glacier fond, devient plus petit et recule. S'il fait à nouveau plus froid, il refera du sur place et construira une autre moraine. S’il fait beaucoup plus froid, le glacier se remettra à grossir et son front progressera vers l’aval.</p><p>Allez jusqu'au bord de l'esplanade, face au lac (là où se trouvait le glacier du Rhône). Vous voyez un peu plus bas la colline de Montriond, couverte de forêt, qui dépasse des bâtiments: c'est une autre moraine! A votre avis, est-elle plus jeune ou plus vieille que celle de Montbenon?</p>",
            },],
        },
        {
            no: 16, 
            lieu: 'Pont Chauderon', 
            accroche: "Qui vient d'abord: la gare ou le quartier?",
            theme: 'BC',
            photo_localisation: ['stop_16.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 16 se trouve au bout de la petite plate-forme de l'ascenseur menant à l'arrêt Vigie du m1.</p>",
            contenu: [{
                'title': "Qui vient d'abord: la gare ou le quartier?",
                'illustration': [['fig_16.jpg',], '&copy; Musée historique de Lausanne, tous droits réservés'],
                'legend': "Photographie de la première gare de Lausanne en 1859. Au moment de sa construction, elle se situe hors de la ville, en pleine campagne.",
                'text': "<p>Au milieu du XIX<sup>e</sup> siècle, le développement du chemin de fer gagne Lausanne et il faut choisir l'emplacement de la gare. Va-t-on l'installer dans le vallon du Flon aux abords de la ville? Sur les quais d'Ouchy pour leur proximité avec le port?</p><p>Ce sera finalement un lieu intermédiaire qui sera choisi, sur un replat naturel au lieu dit &laquo;en Mornex&raquo; qu’une gare en cul de sac sera construite en 1856 pour accueillir les trains en provenance de Bussigny. Elle se situe alors hors de la ville, entourée de prés, de vignes et de jardins.</p><p>Cette petite gare se développe rapidement avec l'ouverture de la ligne du Simplon en 1861 et de la ligne Lausanne-Berne en 1863 pour devenir l’important noeud ferroviaire que l’on connaît aujourd’hui. En même temps, la ville s'étend vers le lac et de nouveaux quartiers recouvrent peu à peu toute la pente jusqu’à Ouchy: la gare de Lausanne se trouve au centre de la nouvelle agglomération.</p><p>Mais la position favorable du vallon du Flon n’est pas oubliée par les constructeurs de chemin de fer: la gare de Sébeillon, un peu à l’ouest d’ici, est mise en service en 1927. Entre 1954 et 1979, elle est reliée aux entrepôts du quartier du Flon par une voie de 980 mètres passant sous le pont Chauderon.</p>",
            },],
        },
        {
            no: 17, 
            lieu: 'Avenue de Provence', 
            accroche: 'Pour protéger vos poumons, retenez votre souffle... ou renoncez à votre voiture!',
            theme: 'BC',
            photo_localisation: ['stop_17.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 17 est situé en haut des escaliers d'accès à l'arrêt Malley du m1, au bord de l'avenue de Provence.</p>",
            contenu: [{
                'title': "Pour protéger vos poumons, retenez votre souffle... ou renoncez à votre voiture!",
                'illustration': [['fig_17.jpg',], 'J.-M. Fallot | modifié S. Martin | Relief 2013 | données OFEV 1991-2012'],
                'legend': "En rouge, la concentration moyenne annuelle de NO2 dans l'air mesurée à la rue César Roux à Lausanne (mg/m<sup>3</sup>). En vert, la limite légale autorisée pour ce polluant.",
                'text': "<p>Les véhicules à moteur sont une des causes principales de la pollution de l'air. Les pots d'échappement laissent s'échapper, entre autres, du dioxyde d'azote (NO2) et des poussières microscopiques appelées particules fines. Ces deux types de polluants causent des problèmes pour l'environnement et pour la santé des habitants qui respirent cet air jour et nuit. C'est surtout en ville, le long des routes très fréquentées, que la pollution est la plus élevée.</p><p>Pour protéger la population, la Confédération a fixé des limites à ne pas dépasser et pris de nombreuses mesures pour limiter la pollution due au trafic, aux chauffages et aux industries. Elle a, par exemple, introduit l’utilisation de filtres (les catalyseurs) et l’obligation d’effectuer des tests anti-pollution pour tous les véhicules.</p><p>Ces mesures se sont montrées efficaces: depuis 1991, la pollution en NO2 baisse. Mais depuis 2005, mauvaise surprise: la pollution ne diminue plus. Aujourd'hui, elle reste toujours supérieure aux limites autorisées! L'effet des nouvelles mesures pour la protection de la qualité de l'air est malheureusement annulé par l'augmentation constante du trafic.</p>",
            },{
                'title': '',
                'text': "<p>Les concentrations moyennes annuelles de dioxyde d'azote (NO2) et des particules fines (PM10) sont mesurées depuis 1991 (1997 pour les PM10, car on mesurait auparavant les poussières totales) à la station fédérale NABEL à la Rue César Roux à Lausanne. Les valeurs limites d'immission (VLI) annuelle de l'OPair (Ordonnance fédérale de la Protection de l'Air) pour le NO2 sont de 30 &mu;g/m<sup>3</sup> et pour les PM10 de 20 &mu;g/m<sup>3</sup>.</p><p>Les concentrations moyennes annuelles de ces 2 polluants ont diminué depuis 1991 grâce aux mesures prises par la Confédération et l'Union Européenne pour réduire les émissions des polluants atmosphériques par le trafic, les chauffages et les industries. Mais cette diminution s'est atténuée depuis l'an 2005 pour le NO2 et les concentrations moyennes annuelles dépassent toujours largement la valeur limite d'immission annuelle pour ce polluant dans le centre de Lausanne au bord des routes à grand trafic. La diminution des concentrations moyennes annuelles des poussières fines (PM10) s'est également arrêtée entre 2000 et 2006, mais elle a repris depuis cette année-là, si bien qu'elles avoisinent dorénavant la valeur limite d'immission annuelle de l'OPair.</p><p>Les concentrations moyennes journalières dépassent aussi les valeurs limites d'immission journalières de l'OPair de 50 &mu;g/m<sup>3</sup> pour les PM10 et de 80 ug/m3 pour le NO2 lorsque des situations anticycloniques persistent durant plusieurs jours en hiver avec des vents faibles et une accumulation d'air froid qui piège les polluants près du sol. Ces valeurs limites d'immission journalières ont ainsi été dépassées durant 11 jours pour les PM10 et 4 jours pour le NO2 à la station de Lausanne en 2012. On peut faire en gros les mêmes observations dans les autres grandes villes de Suisse, aussi bien pour les concentrations moyennes annuelles que journalières de NO2 et des PM10.</p><p>Il convient donc de proposer des mesures d'assainissement supplémentaires dans les agglomérations pour diminuer les concentrations moyennes de certains polluants qui sont encore excessives, en particulier les oxydes d'azote (NOx). D'autant que ces derniers favorisent aussi la formation d'ozone, autre polluant préoccupant en Suisse qui peut atteindre des concentrations excessives, surtout en périphérie et en campagne, par temps bien ensoleillé en saison chaude. Pour cela, des plans des mesures d'assainissement de l'air au sens de l'OPair ont été élaborés pour la plupart des agglomérations en Suisse, afin de remédier aux concentrations excessives de certains polluants. Le plan des mesures OPAir de l'agglomération Lausanne - Morges a été établi en 1995 et réactualisé en 2005. Il comprend une quarantaine de mesures visant à diminuer les émissions des polluants par le trafic, gros émetteur de NOx, ainsi que par les chauffages et les industries. Il concerne environ 40% de la population du canton de Vaud. En l'an 2000, les concentrations moyennes annuelles de NO2 étaient excessives (&gt; 30 &mu;g/m<sup>3</sup>) pour 67% des habitants et 73% des emplois de cette agglomération.</p><p><i>Par: Dr. J.-M. Fallot, Maître d'Enseignement et de Recherche à l'Institut de géographie et durabilité de l'UNIL.</i></p>."
            }],
        },
        {
            no: 18, 
            lieu: "Chemin de l'Usine à Gaz", 
            accroche: 'Malley: la transformation d’une vaste friche industrielle en quartier durable',
            theme: 'B',
            photo_localisation: ['stop_18.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 18 se trouve dans la friche de Malley, face aux voies CFF et à la patinoire.</p>",
            contenu: [{
                'title': "Malley: la transformation d’une vaste friche industrielle en quartier durable",
                'illustration': [['fig_18.jpg',], 'SDIM 2011 | modifié G. Regolini | Relief 2013'],
                'legend': "Les cinq quartiers du secteur Malley et leurs vocations principales (SDIM, modifié).",
                'text': "<p>Vous vous baladez dans un quartier en pleine transformation. Regardez bien autour de vous: d'ici quelques années, Malley-Centre et toute la plaine de Malley vont progressivement se métamorphoser.</p><p>Le schéma directeur intercommunal de Malley (SDIM) prévoit de transformer la vaste friche industrielle en une nouvelle portion de ville à la pointe du respect du développement durable. Au carrefour des communes de Lausanne, Prilly et Renens, la plaine de Malley est parfaitement reliée aux transports en commun (halte CFF Prilly-Malley et ligne de tram t1 qui sera ouverte en 2018) et dispose d’une surface de 83 hectares pour accueillir à terme plus de 10'000 emplois et 8'400 habitants. La reconversion du tissus urbain existant, la création d’espaces publics conviviaux et le respect de l’environnement (espaces verts, mobilité douce, société à 2000 Watts) forment les lignes directrices pour le développement de cinq nouveaux quartiers. Dans quelques années vous travaillerez peut-être dans le futur quartier Strip, passerez votre temps libre à Censuy, ferez vos courses à Malley-Centre ou habiterez le quartier du Chêne ou du Martinet...</p>",
            },{
                'title': 'Liens',
                'text': '<p><a href="http://www.ouest-lausannois.ch">http://www.ouest-lausannois.ch</a></p>',
            }],
        },
        {
            no: 19, 
            lieu: 'Chemin de la Prairie', 
            accroche: "Le retour d'une vieille connaissance: le tramway",
            theme: 'BC',
            photo_localisation: ['stop_19.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 19 est situé à côté des voies, à l'entrée de la gare Malley du métro m1, une des nombreuses lignes de transports public à desservir le quartier.</p>",
            contenu: [{
                'title': "Le retour d'une vieille connaissance: le tramway",
                'illustration': [['fig_19.jpg'], ''],
                'legend': "Le &laquo;réseau-t&raquo; relie les principales zones de développement de l'agglomération Lausanne - Morges à l'aide de moyens de transport public urbain performants.",
                'text': "<p>Supprimé pour des raisons de coûts d'entretien trop élevés et des vitesses de circulation jugées insuffisantes, le tramway va faire sa réapparition dans la capitale vaudoise après une cinquantaine d'années d'absence. Le quartier de Malley-Centre va en effet accueillir d'ici 2018 l'un des arrêts du nouveau tramway reliant dans un premier temps la gare de Renens au Flon.</p><p>La construction de cette nouvelle ligne (t1) s'insère dans la politique de développement d'axes forts desservant les secteurs stratégiques de développement et d'urbanisation de l'agglomération Lausanne-Morges afin de faire face à l'augmentation constante des habitants et des emplois. Le nouveau réseau permet un transport public urbain performant avec des lignes de tramway et des lignes de bus à haut niveau de service offrant une meilleure vitesse d'exploitation et une bonne régularité de desserte.</p><p>Grâce à une série d’aménagements urbains qui entoureront le futur tracé, la réapparition du tram va non seulement changer le visage de Lausanne, mais également certains comportements de mobilité des ses habitants.</p>",
            },],
        },
        {
            no: 20, 
            lieu: 'Vallée de la Jeunesse', 
            accroche: "Une histoire qui finit bien : après avoir offert à Lausanne un de ses plus beaux replats, le Flon traverse le mur qui l'emprisonnait et peut enfin rejoindre le Léman!",
            theme: 'AC',
            photo_localisation: ['stop_20.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 20 se trouve en haut de la Vallée de la Jeunesse, juste en dessous de la place jeu et offre une belle vue en direction du lac.</p>",
            contenu: [{
                'title': "Une histoire qui finit bien : après avoir offert à Lausanne un de ses plus beaux replats, le Flon traverse le mur qui l'emprisonnait et peut enfin rejoindre le Léman!",
                'illustration': [['fig_20a.jpg', 'fig_20b.jpg'], 'S. Martin | Relief 2013 | fond Google Earth'],
                'legend': "En bleu, l'emplacement approximatif du lac alimenté par le Flon et le Galicien. Soulignée d'un trait orange, la crête de moraine de Montbenon qui faisait barrage jusqu'à ce qu'elle soit traversée par le Flon à la hauteur de la Vallée de la Jeunesse.",
                'text': "<p>A partir de la Place de l'Europe (arrêt Lausanne - Flon du métro), le Flon s'est retrouvé bloqué par la grande moraine de Montbenon. Trop difficile pour lui de rejoindre le lac. Il tourne donc vers l'ouest et longe Montbenon à la recherche d'un passage. En chemin, il rencontre un autre cours d'eau, le Galicien. Tous les deux, toujours coincés par la moraine, forment un grand lac à Malley.</p><p>Il pleut: lentement la moraine s'érode et s'affaiblit. L'eau du lac de Malley pousse à l'arrière et tente de traverser. Et un jour, ça y est ! La moraine cède et l'eau s'écoule bruyamment vers le Léman: la vallée de la Jeunesse est née. Le Flon et le Galicien ont enfin trouvé leur chemin. Le lac vidé de son eau laisse une grande plaine, qui sera bien pratique plus tard pour construire le quartier de Malley, des zones industrielles et la ligne de train CFF.</p>",
            },{
                'title': "Liens",
                'illustration': null,
                'legend': null,
                'text': "<p>Informations sur la Vallée de la Jeunesse sur le site des Parcs et promenades de la Ville de Lausanne: <a href=\"http://www.lausanne.ch/ville-de-nature/espaces-verts/parcs-et-promenades/les-sites-de-loisirs/la-vallee-de-la-jeunesse.html\">http://www.lausanne.ch/ville-de-nature/espaces-verts/parcs-et-promenades/les-sites-de-loisirs/la-vallee-de-la-jeunesse.html</a></p>",
            },],
        },
        {
            no: 21, 
            lieu: "Déversoir d'orage", 
            accroche: "Lorsqu'il pleut sur Lausanne, la ville est nettoyée... mais le Léman pollué.",
            theme: 'AB',
            photo_localisation: ['stop_21.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 21 est situé sur le côté ouest de la Vallée de la Jeunesse. Une courte route d'accès mène à la porte – close – du déversoir d'orage: on peut y entendre l'eau couler.</p>",
            contenu: [{
                'title': "Lorsqu'il pleut sur Lausanne, la ville est nettoyée... mais le Léman pollué.",
                'illustration': [['fig_21.jpg',], 'G. Regolini | Relief 2013'],
                'legend': "Schéma du cheminement du cuivre depuis le toit d'une maison jusqu'au Léman.",
                'text': "<p>Lorsque la pluie tombe sur Lausanne, une grande partie de l'eau est dirigée vers les conduites de ruissellement et les déversoirs d'orage. Ce système permet de séparer les eaux claires (eaux de pluie, eaux de surface) des eaux usées (après utilisation domestique ou industrielle) pour diminuer la quantité de l'eau devant être traitée à la station d'épuration et d'ainsi augmenter son rendement.</p><p>Cependant, les eaux claires peuvent transporter des substances indésirables qui ne seront pas traitées et qui rejoignent directement les eaux du Léman. C'est par exemple le cas des métaux lourds, des hydrocarbures et des chlorures. Une étude a montré qu'à Lausanne, 250 kg de cuivre s’écoulent annuellement dans le Léman par les déversoirs d'orage, dont 75% provient des toitures et des caténaires des trolleybus. Le cuivre est dissous dans l'eau et se sédimente dans la baie de Vidy où il peut représenter un risque pour les organismes vivant au fond de l’eau. Des études sont en cours pour proposer des solutions aptes à réduire l'apport de cuivre dans la baie de Vidy et protéger ainsi l'écosystème.</p>",
            },{
                'title': "Référence",
                'illustration': null,
                'legend': null,
                'text': "<p>Chèvre N., Guignard C., Rossi L., Pfeifer H.-R., Bader H.-P., Scheidegger R., Substance flow analysis as a tool for urban water management: the case of copper in Lausanne, Switzerland. <i>Water Science and Technology 63</i>, pp. 1341-1348, 2011.</p>",
            },],
        },
        {
            no: 22, 
            lieu: 'Giratoire Maladière', 
            accroche: 'Métro - boulot - dodo',
            theme: 'B',
            photo_localisation: ['stop_22.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 22 se trouve au centre du giratoire de la Maladière. Pour mieux observer les voitures, vous faire quelques pas dans l'herbe pour vous approcher de la route.</p>",
            contenu: [{
                'title': "Métro - boulot - dodo",
                'illustration': [['fig_22.jpg',], 'OFS/ARE 2005 | modifié G. Regolini | Relief 2013'],
                'legend': "Données du micro-recensement des transports (OFS/ARE, 2005).",
                'text': "<p>Vous vous trouvez à proximité du giratoire de la Maladière. Prenez un moment pour observer les voitures qui empruntent ce giratoire, nœud de circulation important de la ville de Lausanne puisqu'il relie la ville à l'autoroute Lausanne - Genève. Combien de personnes comptez-vous en moyenne par voiture?</p><p>Selon le jour de la semaine et l'heure de votre observation, le taux d'occupation (nombre de passagers par véhicule) varie considérablement. Il est particulièrement bas lors des déplacements pendulaires aux heures de pointes (7h15 - 8h45 et 17h - 18h30) les jours de semaine et plus important entre 14h30 et 16h00 ou le week-end, lorsque des déplacements familiaux ou de loisir sont plus nombreux. </p><p>Le faible remplissage des véhicules lors des heures de pointe génère de nombreux problèmes comme la congestion des routes et la pollution atmosphérique. Pour lutter contre ces problèmes, vous pouvez emprunter les transports en commun et pratiquer le covoiturage. Pensez-y lors de votre prochain déplacement!</p>",
            },],
        },
        {
            no: 23, 
            lieu: 'Stade Pierre de Coubertin', 
            accroche: 'Du foot et du beach volley à la place de la nage et de la pêche',
            theme: 'BC',
            photo_localisation: ['stop_23.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 23 est situé devant l'entrée du stade Pierre de Coubertin.</p>",
            contenu: [{
                'title': "Du foot et du beach volley à la place de la nage et de la pêche",
                'illustration': [['fig_23a.jpg', 'fig_23b.jpg', 'fig_23c.jpg', 'fig_23d.jpg',], '&copy; Photo Aéroport Lausanne, coll. du Musée historique de Lausanne, tous droits réservés'],
                'legend': "Travaux d'aménagement entre Ouchy et Vidy en vu de l'organisation de l'Expo 64. 220'000 m<sup>2</sup> de nouveaux terrains ont été ajoutés.",
                'text': "<p>Là où le sportif d'aujourd'hui joue au football ou au beach volley, le sportif d’hier pouvait faire de la natation. Le rivage du Léman entre Ouchy et Vidy a radicalement changé ces dernières années: en tout, 220'000 m<sup>2</sup> de nouveaux terrains ont été créés artificiellement! Ces importants travaux de comblement ont été réalisés en vue de l'exposition nationale suisse qui s'est déroulée à Lausanne en 1964 (Expo 64). Lors de l’Expo 64, les nouveaux terrains accueillent de nombreux bâtiments et attractions et jusqu'à 100'000 visiteurs par jour. À la fin de l'exposition nationale, la zone est réaménagée pour créer des espaces de détente et des infrastructures pour les Lausannois.</p>",
            },{
                'title': "Liens",
                'illustration': null,
                'legend': null,
                'text': "<p>Histoire de l'Expo 64 sur le site de la ville de Lausanne: <a href=\"http://www.lausanne.ch/ville-culturelle/histoire-et-patrimoine/archives-communales/expositions-virtuelles/expo-64/preparer-l-expo/amenagement-de-vidy.html\">http://www.lausanne.ch/ville-culturelle/histoire-et-patrimoine/archives-communales/expositions-virtuelles/expo-64/preparer-l-expo/amenagement-de-vidy.html</a></p><p>Diaporama sur l'Expo 64: <a href=\"http://webapps.lausanne.ch/ressources/diapos/culture/expo64/index.html\">http://webapps.lausanne.ch/ressources/diapos/culture/expo64/index.html</a></p><p>Archives sonores sur l'Expo 64: <a href=\"http://www.rts.ch/archives/dossiers/3477657-l-expo-64-miroir-d-une-suisse-sure-d-elle.html\">http://www.rts.ch/archives/dossiers/3477657-l-expo-64-miroir-d-une-suisse-sure-d-elle.html</a></p>",
            },],
        },
        {
            no: 24, 
            lieu: 'Ruines du port de Vidy', 
            accroche: 'Que fait un port à 3 mètres au-dessus du niveau du lac et à 250 mètres du rivage?',
            theme: 'AC',
            photo_localisation: ['stop_24.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 24 est accessible en suivant la promenade archéologique à travers les ruines de Vidy. La rampe du port est bien visible, à côté du plan d'eau. Pour en savoir plus sur Lousonna et ses habitants, faites une visite au <strong>musée romain de Lausanne-Vidy</strong>, situé à deux pas d'ici.</p>",
            contenu: [{
                'title': "Que fait un port à 3 mètres au-dessus du niveau du lac et à 250 mètres du rivage?",
                'illustration': [['fig_24a.jpg', 'fig_24b.jpg'], 'P. André | Musée romain de Lausanne-Vidy'],
                'legend': "Reconstitution de Lousonna au IIe siècle après J.-C. (selon P. André). Au centre du cercle rouge, on retrouve la rampe du débarcadère que l'on peut toujours voir aujourd'hui à Vidy.",
                'text': "<p>A Vidy, on trouve les vestiges d'une bourgade gallo-romaine nommée Lousonna (aujourd'hui Lausanne). À cette époque, la bourgade comptait 1500 à 2000 habitants exerçant pour l'essentiel les métiers de marchand, pêcheur ou artisan. On reconnaît les ruines d'une basilique, d'un temple et d'autres bâtiments ainsi que les restes... d'anciens quais! En effet, entre le Ier siècle avant J.-C. et le IVe siècle après, Lousonna était bel et bien implantée au bord du Lemannus (aujourd'hui le Léman). Le niveau du lac était trois mètres plus haut qu'actuellement et les rives du lac se trouvaient alors dans une toute autre position par rapport à leur emplacement actuel.</p><p>Les vestiges de l'ancien port ne sont cependant pas les seuls indices indiquant la position du rivage à l'époque gallo-romaine. À plusieurs endroits sur le pourtour du Léman, le paysage a gardé le souvenir d'anciens niveaux du lac que les géoscientifiques appellent &laquo;terrasses lacustres&raquo;. Ce sont des surfaces planes allongées parallèlement à la rive et plus ou moins larges qui se terminent à l’aval par un talus en pente raide.</p>",
            },{
                'title': "Liens",
                'illustration': null,
                'legend': null,
                'text': "<p>Description de l'agglomération gallo-romaine de Lousonna sur le site du musée de Vidy: <a href=\"http://www1.lausanne.ch/sous-sites/mrv/lousonna.html\">http://www1.lausanne.ch/sous-sites/mrv/lousonna.html</a></p>",
            },],
        },
        {
            no: 25, 
            lieu: 'Siège du CIO', 
            accroche: 'Si cette excursion vous donne soif, buvez une gorgée d’eau!',
            theme: 'AB',
            photo_localisation: ['stop_25.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 25 se trouve près de la fontaine-sculpture, devant le siège du Comité international olympique.</p>",
            contenu: [{
                'title': "Si cette excursion vous donne soif, buvez une gorgée d’eau!",
                'illustration': [['fig_25.jpg', ], 'G. Regolini | Relief 2013 | données EauService'],
                'legend': "<p>Provenance de l'eau potable consommée à Lausanne.</p>",
                'text': "<p>La région lausannoise a besoin d'environ 36 milliards de litres d’eau potable par année, soit le contenu de 14'400 piscines olympiques! Cette eau est utilisée par les ménages (environ 162 litres par jour et par personne), l'industrie, l'artisanat et l'agriculture (au total, cela représente 325 litres par jour et par personne). Savez-vous d’où vient cette énorme quantité d'eau?</p><p>Pour approvisionner Lausanne et 16 communes environnantes, Eauservice, l’organe responsable de la production et de la distribution de l'eau potable, capte des sources du pied du Jura, du Jorat et surtout du Pays d'Enhaut et prélève également de l'eau dans le lac de Bret et dans le Léman (à Lutry et Saint-Sulpice). Selon où vous habitez ou logez, l'eau provient plutôt des sources ou de l'une des usines de traitement.</p>",
            },],
        },
        {
            no: 26, 
            lieu: 'STEP Vidy', 
            accroche: 'STEP Vidy: en première ligne dans le combat contre les micropolluants',
            theme: 'AB',
            photo_localisation: ['stop_26.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 26 est situé devant l'entrée de la STEP de Vidy. Les installations de traitement sont bien cachée par les arbres; elles s'étendent jusqu'à l'autoroute.</p>",
            contenu: [{
                'title': "STEP Vidy: en première ligne dans le combat contre les micropolluants",
                'illustration': [[{file: 'fig_26.mp4', size: [458, 256], poster: 'fig_26.jpg'},], ''],
                'legend': "<p>Parcours des micropolluants domestiques (source: <a href=\"http://www.lausanne.ch/micropolluants\">http://www.lausanne.ch/micropolluants</a>)</p>",
                'text': "<p>Douche et bain, soins du corps, vaisselle, lessive, entretien du ménage, médicaments... la plupart des produits que nous utilisons quotidiennement contiennent des substances synthétiques qui finissent dans les canalisations et, en fin de compte, dans les rivières et les lacs. Si les stations d'épuration (STEP) sont très efficaces pour dégrader les polluants d'origine naturelle, la plupart d’entre elles ne sont pas encore équipées pour éliminer ces substances synthétiques. Pourtant, elles constituent une source de pollution, même à très faible concentration (de l'ordre du micro- ou du nano-gramme par litre) d'où leur nom de &laquo;micropolluants&raquo;. Puisque les effets à long terme sur les écosystèmes aquatiques ou sur les êtres humains sont encore mal connus, il semble judicieux de réduire au maximum les apports des micropolluants.</p><p>La STEP de Vidy a mené des essais pilotes pour le traitement des micropolluants dans le cadre du projet &laquo;Stratégie MicroPoll&raquo; de l'Office fédéral de l'environnement. Les résultats sont concluants: avec un traitement adapté (ex. ozonation et adsorption sur du charbon actif), la charge des micropolluants peut être fortement réduite.</p><p>Avec des gestes simples, vous aussi pouvez contribuer à réduire la charge des micropolluants:</p><ul><li>choisir des produits plus naturels</li><li>doser au plus juste</li><li>se passer des substances inutiles</li></ul>",
            },{
                'title': "Liens",
                'illustration': null,
                'legend': null,
                'text': "<p>Plus d'informations sur: <a href=\"http://www.energie-environnement.ch/maison/micropolluants\">http://www.energie-environnement.ch/maison/micropolluants</a></p>",
            },],
        },
        {
            no: 27, 
            lieu: 'Chamberonne', 
            accroche: 'Les secrets cachés de la Chamberonne',
            theme: 'AC',
            photo_localisation: ['stop_27.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 27 est au bord du lac, à l'embouchure de la Chamberonne.</p>",
            contenu: [{
                'title': "Les secrets cachés de la Chamberonne",
                'illustration': [['fig_27.jpg',], 'L. Rossi et L. Chesaux 2013 | modifié G. Regolini | Relief 2013'],
                'legend': "<p>Concentrations de Diazinon (insecticide utilisé par exemple pour les cultures de colza, des fruits et légumes et les terrains de sport) dans la Chamberonne lors d'un épisode de pluie. Cette substance est très toxique pour les macroinvertébrés des cours d’eau.<br />Les concentrations (en rouge) augmentent en suivant les précipitations et donc le débit (en bleu) indiquant un effet de lessivage des surfaces. En dehors des épisodes de pluies, les concentrations mesurées sont nulles.</p>",
                'text': "<p>La Chamberonne est un affluent typique du Léman, formé par la rencontre entre la Sorge et la Mèbre qui prennent respectivement leur source à 590 m et 800 m dans la molasse du Gros-de-Vaud et du Jorat. Le cours d'eau traverse un paysage d’abord très agricole puis de plus en plus urbain. Entre Crissier et l’EPFL, le cours d'eau est même en grande partie enterré. En s'approchant des rives du lac, la Chamberonne perd ainsi progressivement son naturel.</p><p>Cette artificialisation a aussi un impact sur la qualité de l'eau. Si l'embouchure de la Chamberonne est sans doute un endroit idyllique, il ne faut cependant pas oublier que les eaux de cette rivière sont chargées de substances qui - même à des concentrations très faibles - sont considérées comme polluantes. </p><p>La Chamberonne a fait l'objet de plusieurs études liées à la gestion des crues ou à la qualité de ses eaux. On a mesuré par exemple récemment les concentrations de micropolluants d'origine agricole, urbaine et industrielle. Il s'agit de produits synthétiques (pesticides, substances antibactériennes, additifs industriels) qui peuvent représenter un risque pour les écosystèmes aquatiques et, dans certains cas, pour la santé humaine. L'objectif de ce type d'études est non seulement de mesurer le degré de pollution, mais aussi de développer des outils de gestion pour préserver le milieu naturel afin que l'image idyllique n’ait pas un arrière-goût amer.</p>",
            },{
                'title': "Référence",
                'illustration': null,
                'legend': null,
                'text': "<p>Rossi L, Chesaux L (2013). Sources diffuses de micropolluants dans le Léman : Etude de bassins versants spécifiques et définition d’outils d’extrapolation. Rapport d’étude de l’EPFL, laboratoire de technologie écologique (ECOL), sur mandat de l’Office fédéral de l’environnement (OFEV). EPF Lausanne, 101 p. + Annexes</p>",
            }],
        },
        {
            no: 28, 
            lieu: 'Allée de Dorigny', 
            accroche: "Préférez-vous la natation ou la course à pied? Il y a 11'000 ans, vous n'auriez pas eu le choix: le lac était 10 mètres plus haut et recouvrait tout jusqu'à l'amont de la route!",
            theme: 'AC',
            photo_localisation: ['stop_28.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 28 est situé à l'entrée de l'allée bordée de platanes qui mène à l'UNIL. Arrêtez vous devant le talus bordant les terrains du centre sportif universitaire côté lac.</p>",
            contenu: [{
                'title': "Préférez-vous la natation ou la course à pied ? Il y a 11'000 ans, vous n'auriez pas eu le choix: le lac était 10 mètres plus haut et recouvrait tout jusqu'à l'amont de la route!",
                'illustration': [['fig_28.jpg',], 'S. Martin | Relief 2013'],
                'legend': "Carte des trois niveaux de terrasse entre Malley et Ecublens et schéma en coupe correspondant.",
                'text': "<p>Lausanne n'est pas faite que de pentes raides, mais aussi – parfois – de belles étendues naturellement planes. L'homme a bien exploité ces terrasses comme zones de loisir (Parc de Milan, terrains de ports de Dorigny ou de Chavannes), de transport (avenue de Cour, autoroute et giratoire de la Maladière) ou encore pour construire l'EPFL et l'UNIL.</p><p>On peut observer à Lausanne trois hauteurs de terrasses différentes, chacune correspondant à un ancien niveau du lac. Le niveau le plus haut, 30 mètres au-dessus de l'actuel (parc de Milan, EPFL), est un peu spécial. Ces terrasses se sont formées sur le flanc du glacier du Rhône qui occupait encore il y a 24'000 ans la cuvette du Léman, en faisant comme un immense barrage entre Pully et Ecublens.</p><p>Une fois le glacier disparu, le Léman prend sa place. Mais à Genève, l'embouchure du lac n'est pas entièrement creusée. Le niveau de l'eau se stabilise d’abord à 385 mètres: à cette altitude se forme la terrasse de 10 mètres, ce qui correspond à peu près à la hauteur de la route cantonale. A Genève, le Rhône creuse toujours son lit, mais lentement: à l'époque romaine, le Léman est encore 3 mètres plus haut qu'aujourd'hui. Cette terrasse, occupée par les terrains de sport, est marquée par le premier petit talus qui les sépare de la plage actuelle. A présent, le niveau du lac varie encore, mais artificiellement, grâce aux écluses du Seujet installées sur le Rhône à Genève.</p>",
            },],
        },
        {
            no: 29, 
            lieu: 'Moraine de Dorigny', 
            accroche: 'Depuis la dernière glaciation, il y a des bananes à Lausanne',
            theme: 'AC',
            photo_localisation: ['stop_29.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 29 est se trouve au sommet de la colline, derrière le bâtiment abritant la bibliothèque cantonal universitaire et une des cafétérias de l'UNIL.</p>",
            contenu: [{
                'title': "Depuis la dernière glaciation, il y a des bananes à Lausanne",
                'illustration': [['fig_29a.jpg', 'fig_29b.jpg', 'fig_29c.jpg'], 'S. Martin | Relief 2013 | fond Swisstopo'],
                'legend': "<p>Les bananes soulignent les principales crêtes morainiques de la région lausannoise.</p>",
                'text': "<p>L'Unithèque, bâtiment qui abrite la bibliothèque cantonale et universitaire, porte le surnom sympathique de Banane à cause bien sûr de sa forme courbe. L'architecte a en effet choisi de suivre la courbure naturelle de la colline qui se trouve à l'arrière. Une colline allongée, parallèle au lac, qu'est-ce que cela peut bien être? Si vous avez suivi la balade depuis le début, la réponse ne doit pas être trop difficile à trouver: c'est une moraine laissée là lors du dernier passage du glacier du Rhône.</p><p>La moraine de Dorigny est loin d'être la seule &laquo;banane&raquo; de la région de Lausanne. A chaque fois que l'immense glacier a fait une pause dans son retrait progressif, il a laissé de plus ou moins gros amas de matériaux meubles. Et souvent, ces crêtes de moraine ont obligé les rivières à faire d'étonnants contours. Pour en voir un exemple, observez en passant le cours bien sinueux que suit la Chamberonne!</p>",
            },],
        },
        {
            no: 30, 
            lieu: 'UNIL-Mouline', 
            accroche: 'Le bâtiment Géopolis',
            theme: null,
            photo_localisation: ['stop_30.jpg', 'photo S. Martin | Relief 2013'],
            info_localisation: "<p>L'arrêt 30 correspond à l'arrêt du m1 UNIL-Mouline, devant le bâtiment Géopolis qui accueille depuis 2012 la Faculté des Géosciences et de l'environnement.</p>",
            contenu: [{
                'title': "Le bâtiment Géopolis, construit sur le site d’une ancienne fabrique de meubles, accueille depuis septembre 2012 deux facultés de l’Université de Lausanne: la Faculté des sciences sociales et politiques et la Faculté des géosciences et de l’environnement (FGSE).",
                'illustration': null,
                'legend': null,
                'text': "<p>La FGSE est la plus jeune faculté de l’Université, puisqu’elle a été créée en 2003, dans le sillage des grands bouleversements du paysage universitaire de l’arc lémanique (synergies, transferts et regroupements impliquant les universités de Genève et Lausanne, ainsi que l’EPFL). A l’origine, la FGSE était divisée en six instituts. Depuis 2012, les structures ont été simplifiées : deux instituts (l’Institut des sciences de la Terre (ISTE) et l’Institut de géographie et durabilité (IGD) et un centre de recherche (le Centre de recherche sur l’environnement terrestre, CRET) s’occupent des tâches de recherche, alors que l’Ecole des géosciences a la responsabilité de l’enseignement. Plus d’informations sur <a href=\"http://www.unil.ch/gse\">http://www.unil.ch/gse</a>.</p>",
            },],
        },
        ]
    },
    
    poste: function(no) {   // retourne un poste sur la base du numéro
        for (var i = 0; i < this.data.all.length; i++) {
            if (this.data.all[i].data.no == no) return this.data.all[i].data;
        }
        return null;
    }
});
